version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-rails-image
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - ./:/todo-flutter-rails
      - bundle:/bundle
    ports:
      - "8080:8080"
    links:
      - db
    env_file: ./.env.development
    tty: true
    stdin_open: true
volumes:
  db-data:
    driver: local
  bundle:
    driver: local