source "https://rubygems.org"

gem "rails", "~> 8.0.1"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "jbuilder"
# gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "kamal", require: false
gem "thruster", require: false
# gem "image_processing", "~> 1.2"
gem "devise"
gem "devise_token_auth"
gem "rack-cors"
gem 'active_interaction'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem 'database_cleaner-active_record'
  gem 'dotenv-rails'
end

group :test do
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter'
  gem 'faker'
  gem 'gimei'
end

group :development do
  gem 'annotate'
end

